apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: create-docker-file

spec:
  description: >-
    This task creates a file an pushes it to output 

  workspaces:
    - name: output 

  steps:
  - name: create-file
    image: registry.access.redhat.com/ubi9/ubi-minimal:9.3-1475 #tag: 3.8-alpine

    script: |
      #!/usr/bin/env bash

      cat <<<' 
        FROM registry.access.redhat.com/ubi9/ubi-minimal:9.3-1475
        RUN cd /home
        RUN mkdir -p lightspeed/embedding
        COPY . /home/lightspeed/embedding
        WORKDIR /home/lightspeed/embedding/data' >  $(workspaces.output.path)/dockerfile.output
        


