apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: embedding
spec:
  description: >-
    These task emmbedes the folder files into a vector db 

  workspaces:
    - name: source
      description: shared Workspace containing the data to embed
    - name: output
      description: persisting data output 
  params:

    - name: input-folders
      description: List of folders for processing.
      type: array
      default: [" "]

    - name: model-name
      type: string
      description: LLM model used for embedding  
      default: local:BAAI/bge-base-en


    - name: output-folder
      type: string
      description: collection name in vector DB

    - name: chunk-size
      type: string
      default: "500"
      description: chunk size for embedding

    - name: chunk-overlap
      type: string
      default: "50"
      description: chunk overlap for embedding

  results:
    - name: status
      description: task status 
    - name: folders
      description: folders list convert to string 
  steps:
    - name: convert-to-string
      image: registry.access.redhat.com/ubi9/ubi-minimal:9.3-1552
      args:
        - $(params.input-folders[*])
      script: |
        #!/bin/bash
        for folder in $@
        do
          folders_string+="$folder "
        done

        echo "FOLDERS='${folders_string}'" > /tekton/results/folders 
        cat /tekton/results/folders 


    - name: embedded
      image: "quay.io/redhat_emp1/rag-pipeline-tasks:latest"
      imagePullPolicy: Always
      envFrom:
          - secretRef:
              name: secret-openai
      env:

      - name: MODEL_NAME
        value: $(params.model-name)

      - name: WORKSPACE_OUTPUT_PATH
        value: $(workspaces.output.path)
      - name: TOKENIZERS_PARALLELISM
        value: "false"
      - name: CHUNK_SIZE
        value: $(params.chunk-size)
      - name: CHUNK_OVERLAP
        value: $(params.chunk-overlap)
      script: |
        #!/usr/bin/env bash
        set -eu
        source /tekton/results/folders

        echo "output folder is:"
        echo ${WORKSPACE_OUTPUT_PATH}

        python generate_embeddings.py -mn ${MODEL_NAME} \
                                      -md embeddings_model \
                                      --folders "${FOLDERS} " \
                                      -o ${WORKSPACE_OUTPUT_PATH} \
                                      -c ${CHUNK_SIZE} -l ${CHUNK_OVERLAP} 

        cd $(workspaces.output.path) && zip -r rag.zip * 

        echo ${WORKSPACE_OUTPUT_PATH}
        ls ${WORKSPACE_OUTPUT_PATH}

