apiVersion: v1
kind: LimitRange
metadata:
  name: limitrange
spec:
  limits:
  - default:  # The default limits
      nvidia.com/gpu: '1'
    defaultRequest:  # The default requests
      nvidia.com/gpu: '1'
    max:  # The maximum limits
      nvidia.com/gpu: '1'
    type: Container

