apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  name: privileged-scc
allowPrivilegedContainer: true
readOnlyRootFilesystem: false
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
users:
- system:serviceaccount:lightspeed:pipeline
- system:serviceaccount:lightspeed:default

