kind: Secret
apiVersion: v1
metadata:
  name: github-token
data:
  GITHUB_TOKEN: >-
    Z2l0aHViX3BhdF8xMUFOV0lLTkkweExrNjhEbUN5NENVXzZvZmFXZURVaU5LYzUzaTFCR1oyQ2E0ZkNTQ0RxZUhBdnFxZEo5VDVlRVVKTEw3NFlaMldsVWozcTBC
type: Opaque