apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: rag-data-pipeline
spec: 
      params:
      - name: repo
        type: string
        default: git@github.com:openshift/lightspeed-rag-content.git
        description: Plain text source repo git 
      - name: branch-name
        type: string
        description: The git branch to clone.
        default: main

      - name: input-folders
        description: List of folders for processing.
        type: array
        default: ["/workspace/source/ocp-product-docs-plaintext/4.15"]

      - name: include-evaluation
        type: string
        default: "true"
        description: run auto evaluation 

      - name: release
        type: string
        default: "true"
        description: release artifact true/false

      - name: question-folder
        type: string
        description: Plain text question-folder path
        default: /workdir/questions/openai-gpt-3.5-turbo_no_eval.json

      - name: tag
        type: string
        description: rag results base tag
        default: "chunk-512-overlap-50"

      - name: chunk-size
        type: string
        description: chunk size for embedding
        default: "512"

      - name: chunk-overlap
        type: string
        default: "50"
        description: chunk overlap for embedding

      - name: similarity
        type: string
        default: "1"

      - name: number-of-questions
        type: string
        default: "10"
        description: number of questions generated for evaluation 

      workspaces:     
        - name: shared-workspace  

      tasks:
      - name: git-clone
        taskRef:
          name: git-clone
        workspaces:
            - name: source
              workspace: shared-workspace 
        params:
          - name: url
            value:  "$(params.repo)" 
          - name: revision 
            value: "$(params.branch-name)"  
          - name: subdirectory
            value: ""
          - name: deleteExisting
            value: "true"

      - name: local-embedding
        taskRef:
          name: embedding-v2
        runAfter:
          - git-clone
        workspaces:
          - name: source
            workspace: shared-workspace  
          - name: output
            workspace: shared-workspace 
        params:
            - name: model-name
              value: BAAI/bge-base-en

            - name: output-folder
              value: "$(workspaces.output.path)"

            - name: chunk-size
              value: "$(params.chunk-size)" 

            - name: chunk-overlap
              value: "$(params.chunk-overlap)" 

            - name: input-folders
              value: "$(params.input-folders[*])" 

      - name: bam-chat-v2-evaluation
        taskRef:
          name: evaluation
        when:
          - input: "$(params.include-evaluation)"
            operator: in     
            values: ["true"]
        runAfter:
          - local-embedding
        workspaces:
          - name: persist-source
            workspace: shared-workspace  
          - name: output
            workspace: shared-workspace 
          - name: source
            workspace: shared-workspace  
        params:
            - name: provider
              value: "bam"

            - name: model
              value: ibm/granite-13b-chat-v2

            - name: product-index
              value: "4_15"

            - name: input-persist-dir
              value: "$(workspaces.output.path)/4.15"

            - name: question-folder
              value: "$(params.question-folder)" 

            - name: chunk-size
              value: "$(params.chunk-size)" 

            - name: chunk-overlap
              value: "$(params.chunk-overlap)" 

            - name: similarity
              value: "$(params.similarity)" 

            - name: number-of-questions
              value: "$(params.number-of-questions)"  

      - name: openai-gpt-3-5-turbo-evaluation
        taskRef:
          name: evaluation
        when:
          - input: "$(params.include-evaluation)"
            operator: in
            values: ["true"]
        runAfter:
          - local-embedding
        workspaces:
          - name: persist-source
            workspace: shared-workspace  
          - name: output
            workspace: shared-workspace 
          - name: source
            workspace: shared-workspace  
        params:
            - name: provider
              value: "openai"

            - name: model
              value: gpt-3.5-turbo

            - name: product-index
              value: "4_15"

            - name: input-persist-dir
              value: "$(workspaces.output.path)/4.15"

            - name: question-folder
              value: "$(params.question-folder)"

            - name: chunk-size
              value: "$(params.chunk-size)" 

            - name: chunk-overlap
              value: "$(params.chunk-overlap)" 

            - name: similarity
              value: "$(params.similarity)"  

            - name: number-of-questions
              value: "$(params.number-of-questions)"  



      - name: create-github-release
        taskRef:
          name: create-github-release
        runAfter:
            - bam-chat-v2-evaluation
            - openai-gpt-3-5-turbo-evaluation
        when:
          - input: "$(params.release)"
            operator: in
            values: ["true"]
        workspaces:
          - name: source
            workspace: shared-workspace  
          - name: release-notes
            workspace: shared-workspace 
          - name: output
            workspace: shared-workspace 
        params:
            - name: TAG
              value: $(params.tag)
            - name: REVISION
              value: "main"

